database:
    image: mysql:5.6
    environment:
        - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${DB_DATABASE}"
        - "MYSQL_USER=${DB_USERNAME}" # change to whatever username you want
        - "MYSQL_PASSWORD=${DB_PASSWORD}" #change to the password you want for user
    ports:
        - "3307:3306"
    volumes:
        - "./docker_config/mysql/:/var/lib/mysql"

php72:
    build: ./docker_config
    volumes:
        - ".:/code"
        - "./docker_config/php.ini:/usr/local/etc/php/php.ini"
    working_dir: /code
    links: 
        - database

web:
    image: nginx
    volumes:
        - ".:/code"
        - "./docker_config/nginx-docker.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "8001:80"
    links:
        - php72
            
            